### ISSUE TITLE
Unclear how to use it

### ISSUE THREAD

**Issue by tommythorn** [MicroMinion/curvecp#17]
This looked interesting so I learned about Javascript and node to play with this, but it's unclear is there's a working demo in the repo.  I tried this:

```
2016-03-25 15:39:05 ~/projects/curvecp
git pull
Already up-to-date.
2016-03-25 15:39:16 ~/projects/curvecp
git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
2016-03-25 15:39:18 ~/projects/curvecp
ls
LICENSE     README.md   examples/   package.json*   src/
2016-03-25 15:39:21 ~/projects/curvecp
npm install
curvecp@0.5.1 /Users/tommy/projects/curvecp
├── browser-process-hrtime@0.1.2
├─┬ debug@2.2.0
│ └── ms@0.7.1
├── extend.js@0.0.2
├── inherits@2.0.1
├── int64-buffer@0.1.1
├── is-buffer@1.1.3
├── lodash@3.10.1
├── nanotimer@0.3.14
├─┬ readable-stream-no-buffering@2.0.6
│ ├── core-util-is@1.0.2
│ ├── isarray@0.0.1
│ ├── process-nextick-args@1.0.6
│ ├── string_decoder@0.10.31
│ └── util-deprecate@1.0.2
├── tweetnacl@0.13.3
└── tweetnacl-util@0.13.3

2016-03-25 15:39:26 ~/projects/curvecp
node -v
v5.9.1
2016-03-25 15:39:51 ~/projects/curvecp
node examples/js-test.js
listening
listening
/Users/tommy/projects/curvecp/src/message-stream.js:95
  this._stream.connect(publicKey, connectionInfo)
               ^

TypeError: this._stream.connect is not a function
    at MessageStream.connect (/Users/tommy/projects/curvecp/src/message-stream.js:95:16)
    at UDPServer.connect (/Users/tommy/projects/curvecp/examples/udp.js:54:17)
    at Timeout._onTimeout (/Users/tommy/projects/curvecp/examples/js-test.js:105:26)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

The other example files also doesn't appear much happier.

**Comment by thomasdelaet** [comment]
should be fixed now. could you try again?

**Comment by tommythorn** [comment]
Great thanks, it seems to work.  Now to find out what it does...

It would have been nice with a tiny blurb about the examples to know
what to expect.

**Comment by thomasdelaet** [comment]
Hey Tommy

This is still a very early stage project. Goal is have an implementation of CurveCP in pure javascript that conforms to reference implementation. If you are interested in using this: would be great to let me know your use case so that I can help you set it up / prioritize features you need.

**Comment by tommythorn** [comment]
My interest is mostly academic so please don't pressured.

I want to understand CurveCP better and play with it.  Your implementation appears to be easier to understand and experiment with than the original (I appreciate the refactoring and documentation).  Besides more implementations are always a good thing (expose more corners).
